<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
      <label>
          Изменить email:
          <input type="text" name="user[email]" value="<?= htmlspecialchars($user['email'] ?? ''); ?>">
      </label>
      <?php if (isset($errors['email'])): ?>
          <div><?= $errors['email'] ?></div>
      <?php endif ?>
    </div>
    <input type="submit" value="Update">
</form>