<h1>Users</h1>
<p style="color: green"><?php if (!empty($flash['success'])) {
    foreach ($flash['success'] as $message){
        echo $message;
    }
} ?></p>
<hr>

<form action="/users">
    <input type="search" name ="user" value="<?= htmlspecialchars($userName) ?>">
    <input type="submit" value="Search">
</form>

<hr>

<ul>
    <?php foreach ($users as $user): ?>
    <li><?= $user['nickname'] ?></li>
    <?php endforeach ?>
</ul>