<h1>New User</h1>
<hr>

<form action="/users" method="post">
    <div>
        <label>
            Nickname:
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>">
        </label>
        <?php if (isset($errors['name'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <br>
    <div>
    <label>
        Email:
      <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
      <?php if (isset($errors['email'])): ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </label>
    </div>
    <br>
    <input type="submit" value="Submit">
</form>