<h1>New User</h1>
<hr>

<form action="/users" method="post">
    <div>
        <label>
            Nickname:
            <input type="text" required name="user[name]" value="<?= htmlspecialchars($user['name']) ?>">
        </label>
    </div>
    <br>
    <div>
    <label>
        Email:
      <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
    </label>
    </div>
    <br>
    <input type="submit" value="Submit">
</form>